<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.12" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
		<PackageReference Include="StackExchange.Redis" Version="3.1.31" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\EventManagement.Contracts\EventManagement.Contracts.csproj" />
	  <ProjectReference Include="..\..\EventManagement.Shared\EventManagement.Shared.csproj" />
	  <ProjectReference Include="..\EventsService.Domain\EventsService.Domain.csproj" />
	</ItemGroup>

</Project>
